### ISSUE TITLE
Possible mistake?

### ISSUE THREAD

**Issue by Samisafool** [kskeigrshi/to-arch.sh#24]
https://github.com/kskeigrshi/to-arch.sh/blob/cf2b32da9142391d4457dfc46266f05fa203b891/src/convert-endeavour.sh#L20

What does `LANG=C` even do? Also why not use `removeIfMatched`?

**Comment by kskeigrshi** [comment]
Look at ths comment above the line. LANG=C temporaily sets the locale to the fallback default locale to grep the packages installed in the repo.

**Comment by Samisafool** [comment]
Oh my god! I didn't even bother looking at that, sorry lol
