### ISSUE TITLE
Script doesn't modify /usr/lib/os-release

### ISSUE THREAD

**Issue by Samisafool** [kskeigrshi/to-arch.sh#27]
Title. `/usr/lib/os-release` is basically another `/etc/os-release`.
Then again I just looked through the source so maybe it does do something like that

**Comment by Samisafool** [comment]
Wait nevermind etc/os-release is symlinked to that

**Comment by kskeigrshi** [comment]
lmao yeah, and I just moved to windows and somehow Linux doesnt work on my new machine properly so I'm testing distros on Hyper-V and it's damn fast, but I just have to manage some stuff before I can properly test some distros

**Comment by Samisafool** [comment]
Just use this script on windows lol
