### ISSUE TITLE
Impacts grub if second Manjaro if exists on same drive

### ISSUE THREAD

**Issue by andbenn** [kskeigrshi/to-arch.sh#8]
I had two Manjaro's on my disk:

/dev/sda2 - Manjaro Budgie
/dev/sda3 - Manjaro XFCE

When I ran this script on Manjaro Budgie, things went well.  But I could not boot from Grub into /dev/sda3.

The last line for the entry was:

initrd /boot/intel-ucode.img^/boot/initramfs-linux.img

The ^ character tripped things up.  Had to get grub-customizer, but it has some bugs of it's own.  Hours later, I'm back in business, but with a nested and twisted grub menu flow in /etc/grub.d/4*

**Comment by sugkiy** [comment]
I have a twisted grub menu due to some mistakes. Anyways that's not the problem, it's a problem of multiple arguments getting fed into efibootmgr and I'll try to add a user prompt.

**Comment by sugarykeytone** [comment]
I think this needs and enhancement.

**Comment by kskeigrshi** [comment]
I probably fixed it in the latest release by not touching the UEFI at all. I need more testing.

**Comment by kskeigrshi** [comment]
Yes it's fixed.
